### ISSUE TITLE
Default encoding is not always UTF-8

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-make#33] opened 2015-07-13 21:56 UTC
Thought this was fixed by https://github.com/elm-lang/elm-make/pull/20 but appears to still be broken on some of our build servers :crying_cat_face: (but not every build server, which is fun).

## Symptoms

Running `elm-make` on some Linux machines results in the following:

```
elm-make: ././app/assets/javascripts/Quiz/QuestionStore.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```

This has also been seen previously in https://github.com/elm-lang/elm-compiler/issues/914

## Workaround

The workaround is to run `elm-make` with the `LANG` environment variable set, like so:

`LANG=en_US.UTF-8 elm-make Foo.elm`

**Comment by donutcho** [comment] 2015-07-24 14:29
I'm sorry for the late reply. 
Does it already supports for current version?

LangIssue.elm
```
import Graphics.Element exposing (..)

main : Element
main = show "私"
```

--

On Windows (ja-JP Shift_JIS Vista x64 command prompt):

\> elm make -h
elm-make 0.2 (Elm Platform 0.15.1)
...

\> set LANG=en_US.UTF-8
\> set LANG
LANG=en_US.UTF-8

\> elm make LangIssue.elm
[                                         ] - 0 / 1elm-make.exe: LangIssue.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make.exe: thread blocked indefinitely in an MVar operation

--

Tried with Cygwin: 

$ LANG=en_US.UTF-8 elm make LangIssue.elm
elm-make.exe: LangIssue.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make.exe: thread blocked indefinitely in an MVar operation

--

BTW, I couldn't try the master version for some compiling environment issues.

**Comment by dnalot** [comment] 2015-08-20 07:24
I ran into this tonight too 😭

**Comment by maport** [comment] 2015-08-24 14:01
If it helps with recreation, I ran into this issue when running `elm-make` in a docker container with the following Dockerfile:

```
FROM node:0.12.4
RUN npm install --global elm@2.0.0
ENV ELM_HOME /usr/local/lib/node_modules/elm/share
```

I was able to avoid the error by adding commands to configure the container locale as UTF-8:

```
FROM node:0.12.4
RUN npm install --global elm@2.0.0
ENV ELM_HOME /usr/local/lib/node_modules/elm/share

RUN apt-get update && apt-get install -y \
         locales

RUN dpkg-reconfigure locales && \
         locale-gen C.UTF-8 && \
         update-locale LANG=C.UTF-8

ENV LC_ALL C.UTF-8
```

**Comment by ibukanov** [comment] 2015-09-14 12:50
I experienced this when running elm-reactor against the first example from elm-architecture-tutorial on Ubuntu. I have LANG set to C.UTF-8. The workaround was to run elm-make first. After that elm-reactor worked.

**Comment by deadfoxygrandpa** [comment] 2015-10-13 14:53
I am experiencing this issue now with the new Elm 0.16 alpha 2, on 64-bit Windows 7. My system locale is set to "Chinese (Simplified, PRC)" which is using the CP936 encoding. I've tried setting a LANG environment variable to en_US.CP936, zh_CN, zh_CN.CP936, chs, and chinese-simplified, but it doesn't resolve the issue.

Any ideas?

**Comment by deadfoxygrandpa** [comment] 2015-10-13 15:20
OK, I figured out a workaround by following this: https://stackoverflow.com/questions/14109024/how-to-make-unicode-charset-in-cmd-exe-by-default

Basically, you run `cmd.exe /K chcp 65001` instead of just `cmd.exe` and it will switch to the correct code page.

**Comment by thSoft** [comment] 2015-11-19 23:56
I just encountered this issue when trying to make [Architecture Tutorial Example 1](https://github.com/evancz/elm-architecture-tutorial/tree/master/examples/1) with the [Elm 0.16 Docker image](https://hub.docker.com/r/codesimple/elm/). Unfortunately specifying the LANG environment variable didn't work: :cry: 

```
MacBook-Pro:1 thsoft$ alias elm='docker run -it --rm -v "$(pwd):/code" -w "/code" -e "HOME=/tmp" -e LANG="en_US.UTF-8" -u $UID:$GID -p 8000:8000 codesimple/elm:0.16'
MacBook-Pro:1 thsoft$ elm make
[                                                  ] - 0 / 23elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```

**Comment by maport** [comment] 2015-11-20 13:08
I don't think the `LANG=C.UTF-8` can actually be the fix here, since if I run `env` in the  `codesimple/elm:0.16` docker image I can see the `LANG` setting is already in place:

```sh
$ docker run -it --rm -v "$(pwd):/code" -w "/code" -e "HOME=/tmp" -u $UID:$GID -p 8000:8000 --entrypoint=/usr/bin/env codesimple/elm:0.16
...
TERM=xterm
HOME=/tmp
LANG=C.UTF-8
ELM_VER=0.16
```

Did your remove any `elm-stuff` directory before the `elm make` that failed?

The problem is easily reproducible through with the Architecture Tutorial Example 1:

```sh
$ alias elm='docker run -it --rm -v "$(pwd):/code" -w "/code" -e "HOME=/tmp" -u $UID:$GID -p 8000:8000 codesimple/elm:0.16'
$ cd /tmp
$ git clone https://github.com/evancz/elm-architecture-tutorial.git                                                                      
Cloning into 'elm-architecture-tutorial'...
...
$ cd elm-architecture-tutorial/examples/1
$ elm reactor  
elm reactor 0.16.0
Listening on http://0.0.0.0:8000/
```

Then if I access the application: 

```sh
$ curl http://localhost:8000/Main.elm
...
Downloading elm-lang/core
Downloading evancz/elm-effects
Downloading evancz/elm-html
Downloading evancz/start-app
Downloading evancz/virtual-dom
Packages configured successfully!
elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
...
```

If instead I run `elm make` first, this doesn't occur.

**Comment by jasond-s** [comment] 2015-12-07 17:45
If you are using windows, switch the console default font to one with better UTF support it works fine. `Consolas` is not one of these fonts, `Lucida Console` is however, so I switched my PowerShell over to this. Hope this helps someone while the issue is fixed.

**Comment by grandsong** [comment] 2015-12-11 12:02
I'm also using Windows 7 in Chinese. The default "code page" of cmd.exe is 936 (GBK).

As @deadfoxygrandpa figured out, `cmd.exe /K chcp 65001` is a workaround.

However, it has serious limitations if I want to solve **real-world problems around me** with elm.

As a promising front-end solution, elm really needs to do UTF right to the end. (I know Windows is always a second-class citizen in the web development industry but unfortunately some guys like me still need it.)

This bug is elusive. I guess I'd better describe it a bit.

If there is a **UFT quote character (`“` or `”`)** anywhere in code (comments or strings), my elm-make will fail.

An example is [https://github.com/elm-lang/core/blob/master/src/Graphics/Element.elm#L320](). It frustrated me badly when I just began learning elm.

Chinese characters like "私" will result the same error. Others like "中文", as well as UTF `’`, can pass the compiling but will become **unreadable** in js files.

All these characters are good in the online editor. I guess the bug is just related with cmd.exe.

**Comment by teaspoon** [comment] 2016-01-22 13:07
I am struggling to get Elm working in production with this error. I have tried multiple installations, using npm and also building from source I always receive this error whether or not I try setting LANG.

I am using GHC version 7.10.3 and 
cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library

I have created a new Digital Ocean droplet with Ubuntu 14.04, after creating a user and giving sudo access these are the following commands I run exactly in this order... any advice would be a huge help. 

```
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo apt-get install python-software-properties
sudo add-apt-repository -y ppa:hvr/ghc
sudo apt-get update
sudo apt-get install -y cabal-install-1.22 ghc-7.10.3
cat >> ~/.bashrc <<EOF
export PATH="\$HOME/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.10.3/bin:\$PATH"
EOF
export PATH=~/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH

cabal update
sudo apt-get install git
sudo apt-get install nodejs
sudo apt-get install haskell-platform

sudo -s
echo $PATH
/home/rentalconnect/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.10.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

cat >> ~/.bashrc <<EOF
export PATH="\$HOME/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.10.3/bin:\$PATH"
EOF
export PATH=~/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH

curl https://raw.githubusercontent.com/elm-lang/elm-platform/master/installers/BuildFromSource.hs > BuildFromSource.hs
cd /usr/local/
runhaskell /home/rentalconnect/BuildFromSource.hs 0.16
```

Everthing seems to compile fine but right at the end I get the following message

```
Downloading elm-lang/core
Downloading evancz/elm-html
Downloading evancz/elm-markdown
Downloading evancz/virtual-dom
Packages configured successfully!
elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation

Failed to install elm-reactor-0.16
cabal: Error: some packages failed to install:
elm-reactor-0.16 failed during the building phase. The exception was:
ExitFailure 1
```

Despite this I still try elm-make just on the off chance that may work...

```
~/test$ LANG=en_US.UTF-8 elm-make Accounting.elm 
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 3.0.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Packages configured successfully!
[=========================                         ] - 16 / 32elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```

**Comment by jvoigtlaender** [comment] 2016-01-22 13:14
Is it possible that there is already some Elm version on your machine before you do all that? From what you posted, I suspect that when you run `elm-make` at the end, you are *not* running the version you have installed using with that `runhaskell /home/rentalconnect/BuildFromSource.hs 0.16` just before.

**Comment by jvoigtlaender** [comment] 2016-01-22 13:17
Why do I suspect that? Because I don't see you adding `/usr/local/0.16/.cabal-sandbox/bin` to the path. But you should, according to https://github.com/elm-lang/elm-platform/blob/master/README.md.

**Comment by teaspoon** [comment] 2016-01-22 13:17
As mentioned... it's a clean VM and don't think DigitalOcean include have Elm on the image.... 

```
~/test$ which elm-make
/usr/local/Elm-Platform/0.16/.cabal-sandbox/bin/elm-make
```

**Comment by jvoigtlaender** [comment] 2016-01-22 13:19
Hmm, funny, where do you set that path? It's not in the snippets you showed above.

**Comment by teaspoon** [comment] 2016-01-22 13:21
updated the above comment where I add the path to my profile.

**Comment by jvoigtlaender** [comment] 2016-01-22 13:28
Even that is not very convincing, sorry. What I see now is that you add that path to your profile *after running `BuildFromSource.hs`*. That makes me wonder what version of `elm-make` is running in those lines:
```
Downloading elm-lang/core
Downloading evancz/elm-html
Downloading evancz/elm-markdown
Downloading evancz/virtual-dom
Packages configured successfully!
elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```
purportedly part of the output of
```
runhaskell /home/rentalconnect/BuildFromSource.hs 0.16
```
The thing is: If you haven't added the path `.../Elm-Platform/0.16/.cabal-sandbox/bin/elm-make` to your environment *before* calling `BuildFromSource.hs 0.16`, then *during* that run, the executable `elm-make` should not be found. So you should never see the `Downloading elm-lang/core` lines. But I see them in your output, which makes me believe that it is not true that there is no Elm on your machine before you call `BuildFromSource.hs`.

**Comment by teaspoon** [comment] 2016-01-22 13:32
Okay, I can retry by adding the path before building from source. But there is no Elm before I run these commands, as I say... the vm itself is 2 hours old. Will let you know if I make any further progress.

**Comment by jvoigtlaender** [comment] 2016-01-22 13:35
> But there is no Elm before I run these commands

Prove it by showing console output with an attempted call to `elm-make` *before* the `runhaskell /home/rentalconnect/BuildFromSource.hs 0.16` line. :smile:

**Comment by teaspoon** [comment] 2016-01-22 13:44
I will continue this at home after dinner. Stay tuned... I am not going mad.

**Comment by teaspoon** [comment] 2016-01-25 10:03
I have reset the vm with a new image and tried from scratch using the same commands above, only this time I have added /usr/local/Elm-Platform/0.16/.cabal-sandbox/bin to my path before building from source.

```
root@aberinkula:/root# echo $PATH
/usr/local/Elm-Platform/0.16/.cabal-sandbox/bin:/home/rentalconnect/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.10.3/bin:/home/rentalconnect/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.10.3/bin:/home/rentalconnect/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:/home/rentalconnect/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.10.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@aberinkula:/root# elm-make
elm-make: command not found
root@aberinkula:/root# cd /usr/local/
root@aberinkula:/usr/local# runhaskell /home/rentalconnect/BuildFromSource.hs 0.16

lots of output

Failed to build SideBar.elm

Downloading elm-lang/core
Downloading evancz/elm-html
Downloading evancz/elm-markdown
Downloading evancz/virtual-dom
Packages configured successfully!
elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation

Failed to install elm-reactor-0.16
cabal: Error: some packages failed to install:
elm-reactor-0.16 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by jvoigtlaender** [comment] 2016-01-25 10:07
See the `core` issue I referenced just above your latest comment. I think these are the symbols that kill your install. Unfortunately, I'm very unsuccessful in lobbying @evancz to make a patch release of `core`.

**Comment by teaspoon** [comment] 2016-01-25 10:09
No worries and thanks for the all the help. I understand how these things go, I will try npm one last time and if that does not work I will compile it on my local machine before deploying :(

**Comment by fredcy** [comment] 2016-01-25 15:11
I was getting that `hGetContents` error when running the Haskell web server built from a clone of https://github.com/elm-lang/elm-lang.org. The error went away after I put `export LANG=en_US.UTF-8` in the script that starts the Haskell process. So maybe it's necessary to have that in the exported environment where `runhaskell` runs, not just in the context of `elm-make`.

**Comment by teaspoon** [comment] 2016-01-26 08:23
Hi @fredcy , I actually did try that and it still did not work. I tried again this morning on a new server this time setting the LC_ALL var and installing Elm 0.15 which seemed to work. I still need to test deploys to the box but it seems setting LC_ALL also means not having to prefix elm-make with LANG=....

**Comment by fustkilas** [comment] 2016-02-07 18:49
I'm having the same error on Archlinux. I've tried by using both nodejs-elm from the AUR and by npm, and both times I get the error:

```
[ ] - 0 / 12elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```
`
LANG=en_US.UTF-8 elm make
`

doesn't help either.

Anyone?

**Comment by jvoigtlaender** [comment] 2016-02-07 19:16
Have you tried actually `export`ing `LANG=en_US.UTF-8` rather than just issuing for that specific command?

**Comment by fustkilas** [comment] 2016-02-07 20:11
@jvoigtlaender yes. Same error message.

**Comment by teaspoon** [comment] 2016-02-08 11:04
Please print the outputs of the following commands

locale
cabal --version
ghc --version

**Comment by fustkilas** [comment] 2016-02-09 21:02
@teaspoon, thanks for this hint. After running locale I realised that the locale on my Archlinux setup was messed up.

Specifically, [from here](https://bbs.archlinux.org/viewtopic.php?id=60780), one learns that /etc/locale.gen needs to be edited by uncommenting the required locales, and then running sudo locale-gen to generate the locales.

After doing this, elm-make, elm-repl, everything works. Cheers.

**Comment by teaspoon** [comment] 2016-02-10 08:09
https://media.giphy.com/media/uTuLngvL9p0Xe/giphy.gif

**Comment by jvoigtlaender** [comment] 2016-02-14 20:29
Maybe this is naive, but: Could this issue, and related ones, be solved once and for all by using `setLocaleEncoding utf8` from https://hackage.haskell.org/package/base-4.8.2.0/docs/GHC-IO-Encoding.html at the start of `elm-make` (and possibly other `elm-*` tools)?

**Comment by benjick** [comment] 2016-03-02 11:45
Tried the workaround from @rtfeldman with this:

```
ubuntu@box127:~/ui$ LANG=en_US.UTF-8 node_modules/.bin/elm-test Test/TestRunner.elm
elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```

Any other thing I can try?

**Comment by jvoigtlaender** [comment] 2016-03-02 11:49
See [this comment](https://github.com/elm-lang/elm-make/issues/33#issuecomment-181088515). Also, https://github.com/elm-lang/elm-make/issues/83 fixes this whole issue (according to my tests).

**Comment by benjick** [comment] 2016-03-02 12:15
@jvoigtlaender thanks, but no cigar. Hope your PR gets merged

**Comment by teaspoon** [comment] 2016-03-11 07:43
@benjick Make sure LC_ALL is also set, that will probably work. If it does not then please paste the output from the following commands.

locale
cabal --version
ghc --version

**Comment by benjick** [comment] 2016-03-11 09:30
Thank you @teaspoon 

Here's the output

```
ubuntu@box1059:~/mysite/ui$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
ubuntu@box1059:~/mysite/ui$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
ubuntu@box1059:~/mysite/ui$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
```

Then I tried to do ```LC_ALL=en_GB.UTF-8 cd ui && make test```, here's the output:

```
ubuntu@box1059:~/mysite$ LC_ALL=en_GB.UTF-8 cd ui && make test
npm run test

> elm-webpack@1.0.0 test /home/ubuntu/mysite/ui
> elm-test Test/TestRunner.elm

elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```

**Comment by jvoigtlaender** [comment] 2016-03-11 09:47
@benjick, do what @fustkilas did above? https://github.com/elm-lang/elm-make/issues/33#issuecomment-182066651

**Comment by benjick** [comment] 2016-03-11 10:46
@jvoigtlaender Yes, sort of, there is not `/etc/locale.gen` on the circleci boxes

**Comment by jvoigtlaender** [comment] 2016-03-11 10:52
So are you certain that the locale you are trying to set actually exists on the box where you are trying to run this stuff? Text like
> Before a locale can be enabled on the system, it has to be generated.

on https://wiki.archlinux.org/index.php/Locale indicates that this might be your issue.

**Comment by jvoigtlaender** [comment] 2016-03-11 10:53
Does `en_GB.UTF-8` appear in the output of `locale -a`?

**Comment by benjick** [comment] 2016-03-11 11:25
(I changed to en_US now)

Yes, it does. This is what I'm running `sudo sh -c "echo 'LC_ALL=en_US.UTF-8\nLANG=en_US.UTF-8' >> /etc/environment" && sudo locale-gen en_US.UTF-8 && sudo dpkg-reconfigure locales` and then `locale -a` shows me `en_US.UTF-8` among others.

**Comment by jvoigtlaender** [comment] 2016-03-11 11:36
And after all that? Are you "just" running
```bash
> LC_ALL=en_GB.UTF-8 cd ui && make test
```
as your above console dump suggests, or are you actually doing what you [agreed above to doing](https://github.com/elm-lang/elm-make/issues/33#issuecomment-191215767), namely `export`ing rather than only setting for a specific command?

**Comment by benjick** [comment] 2016-03-11 11:44
Yes, I'm setting both `LC_ALL` and `LANG`

```yml
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
```

**Comment by jvoigtlaender** [comment] 2016-03-11 11:52
Hmm, then I'm afraid I'm running out of ideas. @teaspoon, please take over. :smile:

**Comment by benjick** [comment] 2016-03-11 11:54
@jvoigtlaender Thank you!

**Comment by teaspoon** [comment] 2016-03-14 10:58
Hi @benjick . I have a feeling you need to upgrade your GHC. When I ran Elm 0.16 on GHC 7.6 I had some issues. Upgrade to 7.10... also refer to https://github.com/elm-lang/elm-platform when building from source... having chatted with some folk over on IRC it seems most users are using 7.10.

Let me know how it goes.

**Comment by benjick** [comment] 2016-03-14 14:31
You are correct

```ubuntu@box211:~$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3```

Will report back!

**Comment by teaspoon** [comment] 2016-03-18 08:17
@benjick Please keep us posted as to whether upgrading to GHC 7.10 solved your issue.

**Comment by evancz** [comment] 2016-05-12 08:15
I am not certain, but maybe this became support for a couple different problems. I know @jvoigtlaender found a way to hopefully put things in UTF8 that is now in 0.17. If issues like this persist, we should open a new issue.

Sorry to everyone who had trouble with this!

**Closed by evancz** 2016-05-12 08:15 UTC

**Comment by patrickdet** [comment] 2016-05-25 21:36
```
$ LANG=en_US.UTF-8 elm make
elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```

i still get this issue on 0.16 on my CI server. none of the above suggested solutions work. has anyone found another work-around not documented here?

**Comment by teaspoon** [comment] 2016-05-26 12:15
@patrickdet please paste the output of the following commands
locale
cabal --version
ghc --version
