### ISSUE TITLE
Allow parallelism to be a configuration option

### ISSUE THREAD

**Issue by mceldeen** [elm-lang/elm-make#140] opened 2016-12-12 23:12 UTC
For our CI pipeline, we run containers on very large VMs (i.e. 32 CPUs). `elm-make` seems to be detecting at least 20 of the cores. Unfortunately, our CI environment does not expose the ability to restrict the amount of CPUs visible to the make process inside of the container. This is causing `elm-make` to be a noisy neighbor. We would like the ability to restrict the parallelism of `elm-make`. We could probably have this default to what ever it is now so that you won't see a difference unless you want it to be different.

**Comment by oppegard** [comment] 2016-12-13 22:13
Something equivalent to GNU make's `-j / --jobs` [option](https://www.gnu.org/software/make/manual/make.html#Parallel) would be great.

**Comment by evancz** [comment] 2016-12-22 05:55
This appears to be a duplicate of https://github.com/elm-lang/elm-compiler/issues/1473, or at least closely related. They have a suggestion that seems to help a lot with the underlying problem. In any case, this suggestion is already being tracked there.

Making automated builds is something I am working on, but sorry for the trouble in the meantime!

**Closed by evancz** 2016-12-22 05:55 UTC
