### ISSUE TITLE
Does not respect version ranges

### ISSUE THREAD

**Issue by gurgl** [elm-lang/elm-make#105] opened 2016-06-30 04:41 UTC
{
    "version": "1.0.0",
    "summary": "asdfasdf,
    "repository": "https://github.com/someplace",
    "license": "BSD3",
    "source-directories": [
        "src/."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.0 <= v < 5.0.0",
        "elm-lang/html": "1.0.0 <= v < 1.0.1",
        "elm-lang/svg": "1.0.0 <= v < 1.0.1",
        "elm-lang/virtual-dom": "1.0.0 <= v < 1.0.1",
        "elm-lang/websocket": "1.0.0 <= v < 2.0.0",
        "bartavelle/json-helpers": "1.1.0 <= v < 2.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}

...still after 

> rm -rf elm-stuff
>  elm-make src/MyApp.elm --output myApp.js

it uses/downloads virtual-dom 1.1.0!!

**Comment by gurgl** [comment] 2016-06-30 04:41
for svg and html it does respect version ranges

**Comment by evancz** [comment] 2016-07-01 06:56
Can you open this on https://github.com/elm-lang/elm-package/issues assuming it's not a duplicate of https://github.com/elm-lang/elm-package/issues/213?

**Closed by evancz** 2016-07-01 06:56 UTC
