### ISSUE TITLE
elm-make hangs on type mismatch

### ISSUE THREAD

**Issue by tko** [elm-lang/elm-make#102] opened 2016-06-11 11:22 UTC
Made a small type error that apparently puts elm-make indefinitely in a busy loop:
```elm
minMax list =
  case list of
    x :: xs ->
      let
        step a (lo, hi) = (min a lo, max a hi)
      in
        List.foldl step x xs   -- should be (x, x) here

    [] ->
      Debug.crash "don't care"
```

```elm-make 0.17 (Elm Platform 0.17.0)``` installed with `brew install elm` on El Capitan.

**Comment by evancz** [comment] 2016-06-11 19:44
I think this is a duplicate of https://github.com/elm-lang/elm-compiler/issues/1231

**Closed by evancz** 2016-06-11 19:44 UTC
