### ISSUE TITLE
`--debug` expand contract arrows appear as: 'â–¾'  when html header doesn't include meta 'charset="UTF-8"' 

### ISSUE THREAD

**Issue by NickAger** [elm-lang/elm-make#131] opened 2016-11-17 10:29 UTC
Tested in 0.18 on Safari 10.0.1 and Chrome 54.0.2840.98
* In an empty folder create a modified version of http://elm-lang.org/examples/buttons as `Main.elm` as:

```elm
module Main exposing (..)

import Html exposing (beginnerProgram, div, button, text)
import Html.Events exposing (onClick)


main =
    beginnerProgram { model = { value = 0 }, view = view, update = update }


type alias Model =
    { value : Int
    }


view model =
    div []
        [ button [ onClick Decrement ] [ text "-" ]
        , div [] [ text (toString model.value) ]
        , button [ onClick Increment ] [ text "+" ]
        ]


type Msg
    = Increment
    | Decrement


update msg model =
    case msg of
        Increment ->
            Model (model.value + 1)

        Decrement ->
            Model (model.value - 1)
```

*  generate `elm.js` with: `elm make Main.elm --output elm.js --debug`
* embed in an minimal html page:
```html
<html>
<head>
</head>
<body>
    <div id="main"></div>
    <script type="text/javascript" src="elm.js"></script>
    <script type="text/javascript">
        var mainDiv = document.getElementById('main');
        Elm.Main.embed(mainDiv);
    </script>
</body>
</html>
```
* Open the above html in a browser
* Open the debugger - `Explore History`
* Notice the debugger window shows:
```text
â–¾{
value = 0
}
```

rather than:
```text
▾{
value = 0
}
```

adding the meta tag to the html `<head>`:
```html
<meta charset="UTF-8">
```
causes the correct expand/contract arrows to be show.

* Perhaps `<meta charset="UTF-8">` is a documented requirement that I've missed?
* Could the debugger window include `<meta charset="UTF-8">` in its `<head>`?
* If  `<meta charset="UTF-8">` should be added to the debugger window html, I'm happy to look into this.

**Comment by evancz** [comment] 2016-12-22 05:36
Duplicate of https://github.com/elm-lang/virtual-dom/issues/52

**Closed by evancz** 2016-12-22 05:36 UTC
